### ISSUE TITLE
getSubscription from txPool

### ISSUE THREAD

**Issue by losnappas** [nknorg/nkn-client-js#72]
Hi,

Does `client.getSubscription(topic, addr)` have the capability of also fetching from the Tx pool, like `getSubscribers` does?

It isn't exposed as an option, and I thought asking was quicker than testing this time.

**Comment by yilunzhang** [comment]
It's not available because the subscription info is only determined when a transaction is included into a block.

**Comment by losnappas** [comment]
Alright. I wanted it to work for the d-chat "Joined channel." messages, which are only sent if a person is not subscribed yet.

My current workaround is to first check with `getSubscription`, then with `getSubscribers`, but oftentimes it gives false negatives. It works well enough, I suppose.
